#!/usr/bin/env bash
PREV_LOC="$(pwd)"
TARGET_DIR="$HOME/ros2_ws"
USE_SYMLINK=0

usage() {
  echo "This script cd's to the correct dir (or target dir) to run the colcon build command, and returns to CWD"
  echo "It will also source the new setup.bash file so ros2 commands work correctly"
  echo ""
  echo "Usage: $0 [-s, --symlink ] [-t, --target <target_dir>]"
  echo "       $0 [-h, --help: Show this help]"
  echo ""
  echo "Options:"
  echo "  -s, --symlink               Use the symlink option for colcon build"
  echo "  -t, --target <target_dir>   Specify the target directory. Defaults to: ~/ros2_ws"
  echo "  -h, --help                  Show this help"
  exit 0
}

# Parse commandline options
while [[ "$#" -gt 0 ]]; do
  case "$1" in
    -t|--target)
      TARGET_DIR="$2"
      shift 2
      ;;
    -s|--symlink)
      USE_SYMLINK=1
      shift
      ;;
    -h|--help)
      usage
      ;;
    --) # end of all options
      shift
      break
      ;;
    -?*) # unknown option
      echo "Unknown option: $1"
      usage
      ;;
    *) # no more options
      break
      ;;
  esac
done

echo "Using directory $TARGET_DIR"
cd "$TARGET_DIR"

if [ "$USE_SYMLINK" -eq 1 ]; then
  echo "Building with symlink"
  colcon build --symlink-install
else
  echo "Building without symlink"
	colcon build
fi

cd "$PREV_LOC"

echo "run '. source' to complete the build step"
